New features
nietonfir/RaygunBundle pull request #7
Opened 2017-03-04 14:52 UTC by bertuz

1. It is possible ignoring all the Symfony http exceptions (most of us use them in order to ease the normal flow)
2. A version can be set from the config file
3. A set of default tags can be set from the config file

2017-03-11 00:27 UTC, nietonfir commented
First of all, thx for the PR. I'll add some individual comments tomorrow when time permits. In general feature-specific PRs are simpler to review. ;-)
The tags & version features look ok so far, but regarding the http_exceptions: why would you ignore either all exceptions or none?

The reasoning behind the explicit 404 ignoral is that this kind of exception is triggered a lot e.g.

* Bots/Apps looking for robots.txt/apple-touch-icon/manifest.json/you-name-it
* Dev-Tools searching for source maps
* Invalid links/resources
* …

and might be of any real interest after some time while all other exceptions (especially all kind of server exceptions) should continue to be monitored so they can be handled appropriately.

I'd let the 404 stay and make them e.g. mutually exclusive or re-implement the 404er as a subset of 'all'. This could maybe be extended so that one could pick which kind of exceptions (401, 404, 429, …) should be ignored… But that could be implemented in a follow-up.

2017-03-11 13:02 UTC, bertuz commented
Yep, you are right, I could enhance the ignore functionality in order to ignore specific type of httpexception. If you are not in a hurry I can do it next week ;) 
Basically, I coded that way beacuse all the `HttpException`s we use in our poject are part of a well controlled flow. But I see your point!

2017-03-13 00:55 UTC, nietonfir commented
No hurry, can't wait to see the implementation… ;-)

2017-04-06 11:08 UTC, nietonfir requested changes

2017-04-06 11:08 UTC, nietonfir commented on .gitignore
> +.idea/
Please don't add IDE specific files. You can always either add them to your [global .gitignore ](https://github.com/github/gitignore/tree/master/Global) or use [`assume-unchanged`](https://git-scm.com/docs/git-update-index#git-update-index---no-assume-unchanged) in the repository.

2017-04-06 11:08 UTC, nietonfir commented on DependencyInjection/Configuration.php
> +            ->then(function($v){$v['async'] = false;return $v;})
Please keep the indentation (see [.editorconfig](https://github.com/nietonfir/RaygunBundle/blob/master/.editorconfig)).

2017-04-06 11:08 UTC, nietonfir commented on Resources/config/services.xml
> +           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
Please keep the original indentation for the attributes on those lines.

2017-04-06 11:08 UTC, nietonfir commented on Resources/config/services.xml
> +            </call>
Is there a specific reason for using setter Injection?

2017-04-06 11:08 UTC, nietonfir commented on Resources/config/services.xml
> +
Obsolete newline. ;-)

2017-04-06 11:08 UTC, nietonfir commented on Resources/views/Static/raygun-js.html.twig
> +            e:g})}}(window,document,"script","//cdn.raygun.io/raygun4js/raygun.min.js","rg4js");
Please revert, no need for a reindentation.

2017-04-06 11:08 UTC, nietonfir commented on Resources/views/setup.html.twig
> +    {% endif %}
Please move the if statements to the beginning of the lines.

2017-04-06 11:08 UTC, nietonfir commented on Services/Client.php
> +namespace Nietonfir\RaygunBundle\Services;
Please add the copyright message before the namespace

2017-04-06 11:08 UTC, nietonfir commented on Services/Client.php
> +class Client extends RaygunClient implements NietonfirRaygunClient
`Services` as a namespace is a little bit too generic in my opinion. I'd prefer a dedicated Raygun namespace, so that the override comes out more explicitly (especially with the generic `Client` class name).

2017-04-06 11:08 UTC, nietonfir commented on Services/NietonfirRaygunClient.php
> +interface NietonfirRaygunClient
Please add the copyright message before the namespace. And some phpdoc explaining the function/function parameters.

2017-04-06 11:08 UTC, nietonfir commented on Tests/Twig/RaygunSetupExtensionTest.php
> +                'raygun_app_version' => '1.0.0'),
Please move the closing parenthesis to the next line and align it to the array column (and line 60 as well).

2017-04-06 11:08 UTC, nietonfir commented on Twig/RaygunSetupExtension.php
> +            $globals["raygun_app_version"] = $this->version;
Please use single quotes.

2017-06-20 21:44 UTC, merged

2017-08-12 02:08 UTC, bertuz commented on Resources/config/services.xml
> +            </call>
just a more readable constructor

2017-08-13 22:51 UTC, bertuz commented on Services/Client.php
> +class Client extends RaygunClient implements NietonfirRaygunClient
This is a very Symfony standard in naming. Plus, the full namespace is  `Nietonfir\RaygunBundle\Services`. I'd rather change `Client` into something more meaningful, like `NietonfirRaygunClient`. What do you think?

2017-08-14 00:30 UTC, bertuz commented on Tests/Twig/RaygunSetupExtensionTest.php
> +                'raygun_app_version' => '1.0.0'),
whoops, what a PSR-2 mistake! :)

2017-08-14 00:35 UTC, bertuz commented
@nietonfir I've fixed the code according to your review. You'll find it in the BelkaLab:new_feats branch 👋